// src/pages/BlogDetails.jsx
import { useEffect, useState } from "react";

// Dummy blog JSON (can later be fetched from API)
const blogData = {
  title: "Construction of Lapuwakhola Hydropower Project has been Completed",
  thumbnail:
    "https://sabhapokharihydro.com.np/assets/tenant/uploads/media-uploader/sabhapokharihydro/new-project-791745926655.jpg",
  author: "Sabhapokhari Hydropower",
  date: "27 Apr, 2025",
  tags: ["Hydropower", "Construction"],
  paragraphs: [
    "The construction of the 5 megawatt capacity Lapua Khola small hydropower project being constructed by Sabhapokhari Hydropower Limited of Sankhuwasabha has been completed.",
    "The electricity generated by the project built in Sabhapokhari Rural Municipality-3 of Sankhuwasabha is connected to the national transmission line through a 33 KV transmission line to Tumlingtar substation.",
    "After completing the construction of the project which started in January 077, the project testing work has also been completed at Rohbar of Electricity Authority. Managing Director Sriram Devkota said that the authority will be provided with free electricity for 15 days and commercial production will start from the project from next month.",
    "In the project, a 3,100-meter long headrace pipe and a 600-meter long penstock pipe have been installed and the water from Lufkhola has been pumped to the power house near the local Bahrbise market. This project, financed by the National Commercial Bank, has been completed at a cost of around 1 billion 10 million.",
    "Devkota said that the company has increased the process to issue shares to the general public as the focus has been on completing the project so far."
  ],
};

export default function BlogDetails() {
  const [blog, setBlog] = useState(null);

  useEffect(() => {
    // Simulate fetch (replace with API later)
    setBlog(blogData);
  }, []);

  if (!blog) return <div>Loading...</div>;

  return (
    <div className="rts-blog-list-area">
      <div className="container d-flex justify-content-center">
        <div
          className="row g-5"
          style={{
            maxWidth: "900px",
            width: "100%",
            padding: "30px",
            boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
            borderRadius: "8px",
            backgroundColor: "#fff",
          }}
        >
          <div className="col-12">
            <div className="blog-single-post-listing details mb--0">
              {/* Thumbnail */}
              <div className="thumbnail">
                <img src={blog.thumbnail} alt={blog.title} />
              </div>

              <div className="blog-listing-content">
                {/* User Info */}
                <div className="user-info">
                  <div className="single">
                    <i className="far fa-user-circle"></i>
                    <span>by {blog.author}</span>
                  </div>
                  <div className="single">
                    <i className="far fa-clock"></i>
                    <span>{blog.date}</span>
                  </div>
                  <div className="single">
                    <i className="far fa-tags"></i>
                    <span>{blog.tags.join(", ")}</span>
                  </div>
                </div>

                {/* Title */}
                <h3 className="title animated fadeIn">{blog.title}</h3>

                {/* Content */}
                {blog.paragraphs.map((para, idx) => (
                  <p key={idx} className="disc">
                    {para}
                  </p>
                ))}

                {/* Share Buttons */}
                <div className="details-share mt--30">
                  <h6>Share:</h6>
                  <button>
                    <i className="fab fa-facebook-f"></i>
                  </button>
                  <button>
                    <i className="fab fa-twitter"></i>
                  </button>
                  <button>
                    <i className="fab fa-instagram"></i>
                  </button>
                  <button>
                    <i className="fab fa-linkedin-in"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> 
    </div>
  );
}
